#!/bin/bash
# Transfers a file from our client to a server

# Check if the correct number of parameters were passed
if [[ $# -lt 4 ]]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Get the path to the file, the IP address of the server, the username, and the path to the SSH private key
path_to_file=$1
ip_address=$2
username=$3
path_to_ssh_key=$4

# Disable strict host key checking
ssh-keygen -f "$HOME/.ssh/known_hosts" -R "$ip_address"

# Transfer the file to the server
scp -i "$path_to_ssh_key" "$path_to_file" "$username@$ip_address:~/"
