#!/usr/bin/env bash
# transfers a file from our client to a server
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
path_to_file=$1
username=$3
path_to_ssh_key=$4

# Disabling strict host key checking and transferring the file
if scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@ip:~/"; then
    echo "FILE WAS TRANSFERRED SUCCESSFULLY"
else
    echo "FILE TRANSFER FAILED"
fi
