#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to return "Hello World!" for root path
sudo sed -i 's|root /var/www/html;|root /var/www/html;\n\tlocation = / {\n\t\treturn 200 "Hello World!";\n\t}|' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
