#!/usr/bin/env bash

# Update system packages
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx default page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Start Nginx service
sudo service nginx start
