#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
sudo apt-get update
sudo apt-get -y install haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy
sudo echo "
frontend http_front
  bind *:80
  mode http
  default_backend http_back
backend http_back
   balance roundrobin
   server 272407-web-01 54.227.128.79 check
   echo "   server 272407-web-02 52.201.211.161 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
